name: artemis
version: 6.7.1-beta.1

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  build_config: 1.0.0
  build: 2.0.0
  code_builder: 4.0.0
  collection: ^1.14.12
  dart_style: 2.0.0
  equatable: 2.0.0
  glob: 2.0.1
  gql_code_gen: ^0.1.5
  gql_dedupe_link: ^1.0.10
  gql_exec: ^0.2.4
  gql_link: ^0.3.1-alpha
  gql: ^0.12.3
  http: 0.13.1
  json_annotation: 4.0.1
  meta: ^1.1.8
  path: ^1.6.4
  recase: 4.0.0
  source_gen: 1.0.0
  yaml: 3.1.0

dev_dependencies:
  args: 2.1.0
  build_runner: 2.0.1
  build_test: 2.1.0
  json_serializable: 4.1.1
  pedantic: ^1.9.0
  test: ^1.14.6

dependency_overrides:
  glob: 2.0.1
  dart_style: 2.0.0
  build: 2.0.0
  code_builder: 4.0.0
